name: Build & Deploy to Azure Web App
on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: knavillus10-portfolio-webapp
  PYTHON_VERSION: "3.12"
  NODE_VERSION:  "20"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Copy frontend build to backend
        run: |
          rm -rf backend/app/static || true
          mkdir -p backend/app/static
          cp -r frontend/dist/* backend/app/static/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt --target site-packages

      - name: Zip deploy package
        run: |
          zip -r deploy.zip backend site-packages requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: deploy.zip
